# Schema contract for DE-LU day-ahead forecasting dataset
# Derived strictly from the TXT scope: target (Day-Ahead hourly price) + 3 drivers (Day-Ahead forecasts).
# All timestamps should be normalized to UTC internally to avoid CET/CEST ambiguity.

dataset:
  name: de_lu_day_ahead_market_data
  timezone_policy: UTC  # Convert everything to UTC on ingestion (per TXT risk mitigation).

columns:
  - name: ts_utc
    type: datetime
    units: null
    timezone: UTC
    required: true

  - name: price_da_eur_per_mwh
    type: float
    units: EUR/MWh
    timezone: null
    required: true

  - name: load_forecast_mw
    type: float
    units: MW
    timezone: null
    required: true

  - name: wind_forecast_mw
    type: float
    units: MW
    timezone: null
    required: true

  - name: solar_forecast_mw
    type: float
    units: MW
    timezone: null
    required: true

  # The market is fixed to DE-LU in the frozen scope; include as optional metadata if you store multi-market data later.
  - name: bidding_zone
    type: string
    units: null
    timezone: null
    required: false  # Not required if the pipeline is single-market and encodes DE-LU implicitly.
